#! /bin/bash
if [ $1 == "p" ]; then
		echo adb shell am start -a android.intent.action.CALL -d tel:10086
		adb shell am start -a android.intent.action.CALL -d tel:10086
elif [ $1 == "c" ]; then
		echo adb shell am start -a android.intent.action.DIAL
		adb shell am start -a android.intent.action.DIAL
elif [ $1 == "s" ]; then
		echo adb shell am start -a android.settings.SETTINGS
		adb shell am start -a android.settings.SETTINGS
elif [ $1 == "e" ]; then
		echo adb shell am start -a android.intent.action.WELCOME_EMAIL 
		adb shell am start -a android.intent.action.WELCOME_EMAIL 
fi

