#! /bin/bash
cat ~/bin/a
if [ $1 == "k" ]; then
	sudo /home/ligang/ware/adt-bundle-linux-x86_64-20130219/sdk/platform-tools/adb kill-server
elif [ $1 == "s" ]; then
	sudo /home/ligang/ware/adt-bundle-linux-x86_64-20130219/sdk/platform-tools/adb start-server
fi
